/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/experiences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Опыт работы для таймлайна */
        get: operations["ExperienceController_experiences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проекты */
        get: operations["ExperienceController_projects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Категории навыков */
        get: operations["SkillController_skills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отправить сообщение из формы обратной связи */
        post: operations["ContactController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health-check */
        get: operations["HealthController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ExperienceKind: "Job" | "Project";
        ExperienceDto: {
            /** @example clx123 */
            id: string;
            kind: components["schemas"]["ExperienceKind"];
            /** @example Overchat */
            company: string;
            /** @description Должность/роль на выбранном языке */
            role: string;
            /** @example Удалённо */
            location: string;
            /** @description Период на выбранном языке */
            period: string;
            /** @description Достижения/буллеты */
            bullets: string[];
            /** @description Технологический стек (для проектов) */
            stack: string[];
            /** @example 1 */
            order: number;
        };
        SkillDto: {
            /** @example clx456 */
            id: string;
            /**
             * @description Название категории на выбранном языке
             * @example Фронтенд
             */
            category: string;
            /**
             * @example [
             *       "React",
             *       "Next.js",
             *       "TailwindCSS"
             *     ]
             */
            items: string[];
            /** @example 2 */
            order: number;
        };
        SubmitContactBody: {
            /** @example Кирилл */
            name: string;
            /** @example kirill.burtsev07@gmail.com */
            email: string;
            /** @example Здравствуйте! Хочу обсудить сотрудничество. */
            message: string;
        };
        ContactDto: {
            id: string;
            name: string;
            email: string;
            message: string;
            /** Format: date-time */
            createdAt: string;
        };
        HealthDto: {
            /** @example ok */
            status: string;
            /** Format: date-time */
            time: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ExperienceController_experiences: {
        parameters: {
            query?: {
                lang?: "ru" | "en";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperienceDto"][];
                };
            };
        };
    };
    ExperienceController_projects: {
        parameters: {
            query?: {
                lang?: "ru" | "en";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperienceDto"][];
                };
            };
        };
    };
    SkillController_skills: {
        parameters: {
            query?: {
                lang?: "ru" | "en";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDto"][];
                };
            };
        };
    };
    ContactController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitContactBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactDto"];
                };
            };
        };
    };
    HealthController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
        };
    };
}
